# Generated by Django 5.2.3 on 2025-09-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_customuser_login_token_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iD3UoWP7XuM4llSBDbScDRFkTNwsq7oO', editable=False, max_length=32, unique=True),
        ),
    ]
