# Generated by Django 5.2.3 on 2025-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JSd9ZHWFqDsbUFLYCljRqgqoE4rMatXT', editable=False, max_length=32, unique=True),
        ),
    ]
