# Generated by Django 5.2.3 on 2025-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='iBftYXRksMGkSa832jAVLazDZkWJF36U', editable=False, max_length=32, unique=True),
        ),
    ]
