# Generated by Django 5.2.3 on 2025-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_remove_customuser_role_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='weL9zURoVrx7PTgGn52aJYDKXWh8lyHP', editable=False, max_length=32, unique=True),
        ),
    ]
