# Generated by Django 5.2.3 on 2025-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='UIIobpbe8iZ12kRw7rlcUKpNZ6KDXm2E', editable=False, max_length=32, unique=True),
        ),
    ]
