# Generated by Django 5.2.3 on 2025-10-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qqaa6k3ISYU92Y5OY97whbT6wAOE1nGz', editable=False, max_length=32, unique=True),
        ),
    ]
