# Generated by Django 5.2.3 on 2025-10-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wexunnnjPOZpn1raiDzC3WJd4Zwbe8H9', editable=False, max_length=32, unique=True),
        ),
    ]
