# Generated by Django 5.2.3 on 2025-10-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_customuser_managers_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7TrA3W7jDXJNr4GWZyhFOiNaFVt7M5Uh', editable=False, max_length=32, unique=True),
        ),
    ]
