# Generated by Django 5.2.3 on 2025-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vshKQ6VfV9DS9wJjkpHvQiC9dujmVsdR', editable=False, max_length=32, unique=True),
        ),
    ]
